// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RaiCLI.DbContextEF.Models;

public partial class Prova
{
    public int Id { get; set; }

    public int Idpadre { get; set; }
}